name: flutter_enhanced_barcode_scanner_example
description: Demonstrates how to use the flutter_enhanced_barcode_scanner plugin for Android and iOS.
publish_to: 'none'
version: 2.0.0-nullsafety.0

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1+1
  flutter_plugin_android_lifecycle: ^2.0.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  flutter_enhanced_barcode_scanner:
    path: ../

  pedantic: ^1.10.0-nullsafety.3

flutter:
  uses-material-design: true
